version: '3.9'

services:
  db:
    image: postgres:16
    container_name: dataApapescLocal_bk_1
    restart: unless-stopped
    volumes:
      - postgres_data_bk_1:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"  # VocÃª pode usar 5432:5432 se preferir

  web:
    build: .
    container_name: Apapesc_container_local
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - .:/code
      - ~/.ssh:/root/.ssh:ro       
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data_bk_1:
